apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: prometheus
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
    app: alertmanager
data: 
  config.yml: |
  
   route:
      receiver: 'slack'

  receivers:
      - name: 'slack'
  #       slack_configs:
  #           - send_resolved: true
  #             username: '<username>'
  #             channel: '#<channel-name>'
  #             api_url: '<incomming-webhook-url>'