apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        image: prom/alertmanager
        name: alertmanager
        ports:
        - containerPort: 9093
        resources: {}
        volumeMounts:
        - mountPath: /etc/alertmanager/
          name: alertmanager-claim0
      restartPolicy: Always
      volumes:
      - name: alertmanager-claim0
        persistentVolumeClaim:
          claimName: alertmanager-claim0
status: {}
