#apiVersion: v1
#kind: Service
#metadata:
#  namespace: prometheus
#  annotations:
#    kompose.cmd: kompose convert
#    kompose.version: 1.17.0 (a74acad)
#  creationTimestamp: null
#  labels:
#    io.kompose.service: cadvisor
#  name: cadvisor
#spec:
#  ports:
#  - name: "8080"
#    port: 8080
#    targetPort: 8080
#  selector:
#    io.kompose.service: cadvisor
#status:
#  loadBalancer: {}

apiVersion: v1
kind: Service
metadata:
  namespace: prometheus
  name: cadvisor-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: cadvisor
  type: NodePort



