apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: prometheus
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cadvisor
    spec:
      containers:
      - image: google/cadvisor
        name: cadvisor
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /rootfs
          name: cadvisor-claim0
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-claim1
        - mountPath: /sys
          name: cadvisor-claim2
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-claim3
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: cadvisor-claim0
        persistentVolumeClaim:
          claimName: cadvisor-claim0
          readOnly: true
      - name: cadvisor-claim1
        persistentVolumeClaim:
          claimName: cadvisor-claim1
      - name: cadvisor-claim2
        persistentVolumeClaim:
          claimName: cadvisor-claim2
          readOnly: true
      - name: cadvisor-claim3
        persistentVolumeClaim:
          claimName: cadvisor-claim3
          readOnly: true
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
