apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prometheus
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter-claim2
  name: node-exporter-claim2
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
