apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    namespace: prometheus
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node-exporter
    spec:
      containers:
      - args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points
        - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($|/)
        image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
        resources: {}
        volumeMounts:
        - mountPath: /host/proc
          name: node-exporter-claim0
          readOnly: true
        - mountPath: /host/sys
          name: node-exporter-claim1
          readOnly: true
        - mountPath: /rootfs
          name: node-exporter-claim2
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: node-exporter-claim0
        persistentVolumeClaim:
          claimName: node-exporter-claim0
          readOnly: true
      - name: node-exporter-claim1
        persistentVolumeClaim:
          claimName: node-exporter-claim1
          readOnly: true
      - name: node-exporter-claim2
        persistentVolumeClaim:
          claimName: node-exporter-claim2
          readOnly: true
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
