apiVersion: v1
kind: Service
metadata:
  annotations:
    namespace: prometheus
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  ports:
  - name: "9100"
    port: 9100
    targetPort: 9100
  selector:
    io.kompose.service: node-exporter
status:
  loadBalancer: {}
