apiVersion: v1
kind: Service
metadata:
  namespace: prometheus
  name: prometheus-service
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: prometheus
  type: NodePort