apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: prometheus
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-data
  name: prometheus-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
